name: github actions demo

on:
  push:
    branches: [ bazel_demo ]

jobs:
  job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bazelbuild/setup-bazelisk@v1
    - run: |
        cd bazel_demo/stage1
        bazel build //main:hello
        ls

        
    
