name: github actions demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest,macos-latest]
        python-version: [3.6,3.7]
    # matrix.os可作为变量使用
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: build hello.py
      run:
        python hello.py
  job2:
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest,macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: windows build hello.cpp
      if: matrix.os=='windows-latest'
      run: |
        make
        echo "执行./hello.exe"
        ./hello.exe
    - name: linux or mac build hello.cpp
      #多个条件判断需要使用${{}}
      if: ${{matrix.os=='ubuntu-latest' || matrix.os=='macos-latest'}}
      #d多条命令需要使用"|"
      run: |
        make
        echo "执行./hello"
        ./hello

    
