name: github actions demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    # matrix.os可作为变量使用
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: linux and mac build
      #多个条件判断需要使用${{}}
      if: ${{matrix.os=='ubuntu-latest' || matrix.os=='macos-latest'}}
      #d多条命令需要使用"|"
      run: |
        make
        ./hello
        make clean
    - name: windows build
      if: matrix.os=='windows-latest'
      run: |
        echo "github.workspace is ${{github.workspace}}"
        ls ${{github.workspace}}
    
