name: github actions demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    runs-on: ${{matrix.os}}
    if: matrix.os==ubuntu-latest || matrix.os==macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: linux and mac build
      run: |
        make
        ./hello
        make clean
